# Generated by Django 5.0.6 on 2024-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Стоимость в рублях со скидкой'),
        ),
    ]
