# Generated by Django 5.0.6 on 2024-06-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7, null=True, verbose_name='Стоимость в рублях со скидкой'),
        ),
    ]
