# Generated by Django 5.0.6 on 2024-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Скидка в %'),
        ),
    ]
