# Generated by Django 5.0.6 on 2024-06-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_with_discount',
        ),
    ]
