# Generated by Django 5.0.6 on 2024-06-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_products_price_with_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='descripion',
            new_name='description',
        ),
    ]
